# Generated by Django 5.2.1 on 2025-07-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='verdict',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('COMPILE_ERROR', 'Compilation Error'), ('SYSTEM_ERROR', 'System Error')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256, help_text='MB'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, help_text='Second'),
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_output', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Second', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='MB', null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILE_ERROR', 'Compilation Error'), ('SYSTEM_ERROR', 'System Error')], default='PENDING', max_length=20)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.testcase')),
            ],
        ),
    ]
